package uk.ac.openmf.utils;

public class OpenMFConstants {

	public static final String ENTITY_USER_TYPE_GAE = "GaeUser";
	public static final String FIELD_NAME_USER_AUTHORITIES = "authorities";
	
	public static final String FIELD_VALUE_ZERO = "0.00";

	public static final String FIELD_NAME_ID = "id";
	public static final String FIELD_NAME_USERID = "userId";
	public static final String FIELD_NAME_USERNAME = "username";
	public static final String FIELD_NAME_CREATEDBY = "createdBy";
	public static final String FIELD_NAME_ROLE = "role";
	public static final String FIELD_NAME_ROLEID = "roleId";
	public static final String FIELD_NAME_TIMESTAMP = "timestamp";
	public static final String FIELD_NAME_DESCRIPTION = "description";
	public static final String FIELD_NAME_EMAIL = "email";
	public static final String FIELD_NAME_FORENAME = "forename";
	public static final String FIELD_NAME_SURNAME = "surname";
	public static final String FIELD_NAME_ENABLED = "enabled";
	public static final String FIELD_NAME_SUPERVISOR = "supervisor";
	public static final String FIELD_NAME_ADDRESS = "address";
	public static final String FIELD_NAME_MAIN_OFFICE = "main_office";
	public static final String FIELD_NAME_CONTACT = "contact";
	public static final String FIELD_NAME_PASSWORD = "password";
	public static final String FIELD_NAME_RATEOFINTEREST = "rateofinterest";
	public static final String FIELD_NAME_CLOSEDATE = "closedate";
	public static final String FIELD_NAME_STARTDATE = "startdate";
	public static final String FIELD_NAME_LOANCODE = "loancode";
	public static final String FIELD_NAME_PRODUCTNAME = "productname";
	public static final String FIELD_NAME_ACTIVE = "active";
	public static final String FIELD_NAME_MIDNAME = "midname";
	public static final String FIELD_NAME_DATEOFBIRTH = "dateofbirth";
	public static final String FIELD_NAME_CLIENTTYPE = "clienttype";
	public static final String FIELD_NAME_EXTERNALID = "externalId";
	public static final String FIELD_NAME_GENDER = "gender";
	public static final String FIELD_NAME_CLIENTCLASSIFICATION = "clientclassification";
	public static final String FIELD_NAME_ACTIVATIONDATE = "activationdate";
	public static final String FIELD_NAME_SUBMITTEDON = "submittedon";
	public static final String FIELD_NAME_ACCOUNTNUMBER = "accountnumber";
	public static final String FIELD_NAME_REPAYMENTFREQUENCY = "repaymentfrequency";
	public static final String FIELD_NAME_REPAYMENTPERIOD = "repaymentperiod";
	public static final String FIELD_NAME_LOANAMOUNT = "loanamount";
	public static final String FIELD_NAME_SAVINGSCODE = "savingscode";
	public static final String FIELD_NAME_TENURE = "tenure";
	public static final String FIELD_NAME_DEPOSITFREQUENCY = "depositfrequency";
	public static final String FIELD_NAME_SAVINGSAMOUNT = "savingsamount";
	public static final String FIELD_NAME_SAVINGSTYPE = "savingstype";
	public static final String FIELD_NAME_ELIGIBLE = "eligible";
	public static final String FIELD_NAME_BLACKLISTED = "blacklisted";
	public static final String FIELD_NAME_LOANTYPE = "loantype";
	public static final String FIELD_NAME_BALANCE = "balance";
	public static final String FIELD_NAME_CLIENTID = "clientId";
	public static final String FIELD_NAME_LOANACCOUNTNUMBER = "loanaccountnumber";
	public static final String FIELD_NAME_DISBURSEDON = "disbursedon";
	public static final String FIELD_NAME_LOANPURPOSE = "loanpurpose";
	public static final String FIELD_NAME_APPROVEDAMOUNT = "approvedamount";
	public static final String FIELD_NAME_DISBURSEDAMOUNT = "disbursedamount";
	public static final String FIELD_NAME_ARREARSBY = "arrearsby";
	public static final String FIELD_NAME_LOANSTARTDATE = "loanstartdate";
	public static final String FIELD_NAME_LOANCLOSEDATE = "loanclosedate";
	public static final String FIELD_NAME_INTERESTCALCPERIOD = "interestcalcperiod";
	public static final String FIELD_NAME_BALANCEOUTSTANDINGAMOUNT = "balanceoutstandingamount";
	public static final String FIELD_NAME_PRINCIPALDUEAMOUNT = "principaldueamount";
	public static final String FIELD_NAME_TOTALNUMREPAYMENTS = "totalnumrepayments";
	public static final String FIELD_NAME_NUMREPAYMENTSMADE = "numrepaymentsmade";
	public static final String FIELD_NAME_APPROVEDON = "approvedon";
	public static final String FIELD_NAME_MATURESON = "matureson";
	public static final String FIELD_NAME_APPROVEDBY = "approvedby";
	public static final String FIELD_NAME_FIELDOFFICER = "fieldofficer";
	public static final String FIELD_NAME_LOANOFFICER = "loanofficer";
	public static final String FIELD_NAME_TOTALREPAYMENTAMOUNT = "totalrepaymentamount";
	public static final String FIELD_NAME_INTERESTREPAYMENTAMOUNT = "interestrepaymentamount";
	public static final String FIELD_NAME_PENALTIES = "penalties";
	public static final String FIELD_NAME_FEES = "fees";
	public static final String FIELD_NAME_DEFAULTED = "defaulted";
	public static final String FIELD_NAME_NUMPAYMENTSMISSED = "numpaymentsmissed";

}
