/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-14 at 11:04:28 UTC 
 * Modify at your own risk.
 */

package com.appspot.openmicrofinance.taskapi;

/**
 * Service definition for Taskapi (v1).
 *
 * <p>
 * An API to manage tasks
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TaskapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Taskapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the taskapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://openmicrofinance.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "taskapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Taskapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Taskapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "add".
   *
   * This request holds the parameters needed by the the taskapi server.  After setting any optional
   * parameters, call the {@link Add#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Add add() throws java.io.IOException {
    Add result = new Add();
    initialize(result);
    return result;
  }

  public class Add extends TaskapiRequest<com.appspot.openmicrofinance.taskapi.model.OpenMFTask> {

    private static final String REST_PATH = "addOpenMFTask";

    /**
     * Create a request for the method "add".
     *
     * This request holds the parameters needed by the the taskapi server.  After setting any optional
     * parameters, call the {@link Add#execute()} method to invoke the remote operation. <p> {@link
     * Add#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Add() {
      super(Taskapi.this, "POST", REST_PATH, null, com.appspot.openmicrofinance.taskapi.model.OpenMFTask.class);
    }

    @Override
    public Add setAlt(java.lang.String alt) {
      return (Add) super.setAlt(alt);
    }

    @Override
    public Add setFields(java.lang.String fields) {
      return (Add) super.setFields(fields);
    }

    @Override
    public Add setKey(java.lang.String key) {
      return (Add) super.setKey(key);
    }

    @Override
    public Add setOauthToken(java.lang.String oauthToken) {
      return (Add) super.setOauthToken(oauthToken);
    }

    @Override
    public Add setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Add) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Add setQuotaUser(java.lang.String quotaUser) {
      return (Add) super.setQuotaUser(quotaUser);
    }

    @Override
    public Add setUserIp(java.lang.String userIp) {
      return (Add) super.setUserIp(userIp);
    }

    @Override
    public Add set(String parameterName, Object value) {
      return (Add) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getTask".
   *
   * This request holds the parameters needed by the the taskapi server.  After setting any optional
   * parameters, call the {@link GetTask#execute()} method to invoke the remote operation.
   *
   * @param taskId
   * @return the request
   */
  public GetTask getTask(java.lang.String taskId) throws java.io.IOException {
    GetTask result = new GetTask(taskId);
    initialize(result);
    return result;
  }

  public class GetTask extends TaskapiRequest<com.appspot.openmicrofinance.taskapi.model.OpenMFTask> {

    private static final String REST_PATH = "openmftask/{taskId}";

    /**
     * Create a request for the method "getTask".
     *
     * This request holds the parameters needed by the the taskapi server.  After setting any optional
     * parameters, call the {@link GetTask#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetTask#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param taskId
     * @since 1.13
     */
    protected GetTask(java.lang.String taskId) {
      super(Taskapi.this, "GET", REST_PATH, null, com.appspot.openmicrofinance.taskapi.model.OpenMFTask.class);
      this.taskId = com.google.api.client.util.Preconditions.checkNotNull(taskId, "Required parameter taskId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTask setAlt(java.lang.String alt) {
      return (GetTask) super.setAlt(alt);
    }

    @Override
    public GetTask setFields(java.lang.String fields) {
      return (GetTask) super.setFields(fields);
    }

    @Override
    public GetTask setKey(java.lang.String key) {
      return (GetTask) super.setKey(key);
    }

    @Override
    public GetTask setOauthToken(java.lang.String oauthToken) {
      return (GetTask) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTask setQuotaUser(java.lang.String quotaUser) {
      return (GetTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTask setUserIp(java.lang.String userIp) {
      return (GetTask) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String taskId;

    /**

     */
    public java.lang.String getTaskId() {
      return taskId;
    }

    public GetTask setTaskId(java.lang.String taskId) {
      this.taskId = taskId;
      return this;
    }

    @Override
    public GetTask set(String parameterName, Object value) {
      return (GetTask) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "list".
   *
   * This request holds the parameters needed by the the taskapi server.  After setting any optional
   * parameters, call the {@link List#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public List list() throws java.io.IOException {
    List result = new List();
    initialize(result);
    return result;
  }

  public class List extends TaskapiRequest<com.appspot.openmicrofinance.taskapi.model.OpenMFTaskCollection> {

    private static final String REST_PATH = "openmftaskcollection";

    /**
     * Create a request for the method "list".
     *
     * This request holds the parameters needed by the the taskapi server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation. <p> {@link
     * List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected List() {
      super(Taskapi.this, "GET", REST_PATH, null, com.appspot.openmicrofinance.taskapi.model.OpenMFTaskCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public List setAlt(java.lang.String alt) {
      return (List) super.setAlt(alt);
    }

    @Override
    public List setFields(java.lang.String fields) {
      return (List) super.setFields(fields);
    }

    @Override
    public List setKey(java.lang.String key) {
      return (List) super.setKey(key);
    }

    @Override
    public List setOauthToken(java.lang.String oauthToken) {
      return (List) super.setOauthToken(oauthToken);
    }

    @Override
    public List setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (List) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public List setQuotaUser(java.lang.String quotaUser) {
      return (List) super.setQuotaUser(quotaUser);
    }

    @Override
    public List setUserIp(java.lang.String userIp) {
      return (List) super.setUserIp(userIp);
    }

    @Override
    public List set(String parameterName, Object value) {
      return (List) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listByUsername".
   *
   * This request holds the parameters needed by the the taskapi server.  After setting any optional
   * parameters, call the {@link ListByUsername#execute()} method to invoke the remote operation.
   *
   * @param omfuId
   * @return the request
   */
  public ListByUsername listByUsername(java.lang.String omfuId) throws java.io.IOException {
    ListByUsername result = new ListByUsername(omfuId);
    initialize(result);
    return result;
  }

  public class ListByUsername extends TaskapiRequest<com.appspot.openmicrofinance.taskapi.model.OpenMFTaskCollection> {

    private static final String REST_PATH = "openmftaskcollection/{omfuId}";

    /**
     * Create a request for the method "listByUsername".
     *
     * This request holds the parameters needed by the the taskapi server.  After setting any optional
     * parameters, call the {@link ListByUsername#execute()} method to invoke the remote operation.
     * <p> {@link ListByUsername#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param omfuId
     * @since 1.13
     */
    protected ListByUsername(java.lang.String omfuId) {
      super(Taskapi.this, "GET", REST_PATH, null, com.appspot.openmicrofinance.taskapi.model.OpenMFTaskCollection.class);
      this.omfuId = com.google.api.client.util.Preconditions.checkNotNull(omfuId, "Required parameter omfuId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListByUsername setAlt(java.lang.String alt) {
      return (ListByUsername) super.setAlt(alt);
    }

    @Override
    public ListByUsername setFields(java.lang.String fields) {
      return (ListByUsername) super.setFields(fields);
    }

    @Override
    public ListByUsername setKey(java.lang.String key) {
      return (ListByUsername) super.setKey(key);
    }

    @Override
    public ListByUsername setOauthToken(java.lang.String oauthToken) {
      return (ListByUsername) super.setOauthToken(oauthToken);
    }

    @Override
    public ListByUsername setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListByUsername) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListByUsername setQuotaUser(java.lang.String quotaUser) {
      return (ListByUsername) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListByUsername setUserIp(java.lang.String userIp) {
      return (ListByUsername) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String omfuId;

    /**

     */
    public java.lang.String getOmfuId() {
      return omfuId;
    }

    public ListByUsername setOmfuId(java.lang.String omfuId) {
      this.omfuId = omfuId;
      return this;
    }

    @Override
    public ListByUsername set(String parameterName, Object value) {
      return (ListByUsername) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "remove".
   *
   * This request holds the parameters needed by the the taskapi server.  After setting any optional
   * parameters, call the {@link Remove#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public Remove remove(java.lang.Long id) throws java.io.IOException {
    Remove result = new Remove(id);
    initialize(result);
    return result;
  }

  public class Remove extends TaskapiRequest<Void> {

    private static final String REST_PATH = "openmftask/{id}";

    /**
     * Create a request for the method "remove".
     *
     * This request holds the parameters needed by the the taskapi server.  After setting any optional
     * parameters, call the {@link Remove#execute()} method to invoke the remote operation. <p> {@link
     * Remove#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected Remove(java.lang.Long id) {
      super(Taskapi.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public Remove setAlt(java.lang.String alt) {
      return (Remove) super.setAlt(alt);
    }

    @Override
    public Remove setFields(java.lang.String fields) {
      return (Remove) super.setFields(fields);
    }

    @Override
    public Remove setKey(java.lang.String key) {
      return (Remove) super.setKey(key);
    }

    @Override
    public Remove setOauthToken(java.lang.String oauthToken) {
      return (Remove) super.setOauthToken(oauthToken);
    }

    @Override
    public Remove setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Remove) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Remove setQuotaUser(java.lang.String quotaUser) {
      return (Remove) super.setQuotaUser(quotaUser);
    }

    @Override
    public Remove setUserIp(java.lang.String userIp) {
      return (Remove) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public Remove setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public Remove set(String parameterName, Object value) {
      return (Remove) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the the taskapi server.  After setting any optional
   * parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param taskId
   * @return the request
   */
  public Update update(java.lang.String taskId) throws java.io.IOException {
    Update result = new Update(taskId);
    initialize(result);
    return result;
  }

  public class Update extends TaskapiRequest<com.appspot.openmicrofinance.taskapi.model.OpenMFTask> {

    private static final String REST_PATH = "openmftask/{taskId}";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the taskapi server.  After setting any optional
     * parameters, call the {@link Update#execute()} method to invoke the remote operation. <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param taskId
     * @since 1.13
     */
    protected Update(java.lang.String taskId) {
      super(Taskapi.this, "PUT", REST_PATH, null, com.appspot.openmicrofinance.taskapi.model.OpenMFTask.class);
      this.taskId = com.google.api.client.util.Preconditions.checkNotNull(taskId, "Required parameter taskId must be specified.");
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String taskId;

    /**

     */
    public java.lang.String getTaskId() {
      return taskId;
    }

    public Update setTaskId(java.lang.String taskId) {
      this.taskId = taskId;
      return this;
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Taskapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Taskapi}. */
    @Override
    public Taskapi build() {
      return new Taskapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TaskapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTaskapiRequestInitializer(
        TaskapiRequestInitializer taskapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(taskapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
