/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-14 at 11:04:28 UTC 
 * Modify at your own risk.
 */

package com.appspot.openmicrofinance.taskapi.model;

/**
 * Model definition for OpenMFTask.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the taskapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class OpenMFTask extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String accountnumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String amount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String assignedto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cashier;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String collectiontype;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String createdById;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String dateassigned;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String datecompleted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean newclient;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String taskId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long timestamp;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccountnumber() {
    return accountnumber;
  }

  /**
   * @param accountnumber accountnumber or {@code null} for none
   */
  public OpenMFTask setAccountnumber(java.lang.String accountnumber) {
    this.accountnumber = accountnumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAmount() {
    return amount;
  }

  /**
   * @param amount amount or {@code null} for none
   */
  public OpenMFTask setAmount(java.lang.String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAssignedto() {
    return assignedto;
  }

  /**
   * @param assignedto assignedto or {@code null} for none
   */
  public OpenMFTask setAssignedto(java.lang.String assignedto) {
    this.assignedto = assignedto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCashier() {
    return cashier;
  }

  /**
   * @param cashier cashier or {@code null} for none
   */
  public OpenMFTask setCashier(java.lang.String cashier) {
    this.cashier = cashier;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCollectiontype() {
    return collectiontype;
  }

  /**
   * @param collectiontype collectiontype or {@code null} for none
   */
  public OpenMFTask setCollectiontype(java.lang.String collectiontype) {
    this.collectiontype = collectiontype;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreatedById() {
    return createdById;
  }

  /**
   * @param createdById createdById or {@code null} for none
   */
  public OpenMFTask setCreatedById(java.lang.String createdById) {
    this.createdById = createdById;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDateassigned() {
    return dateassigned;
  }

  /**
   * @param dateassigned dateassigned or {@code null} for none
   */
  public OpenMFTask setDateassigned(java.lang.String dateassigned) {
    this.dateassigned = dateassigned;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDatecompleted() {
    return datecompleted;
  }

  /**
   * @param datecompleted datecompleted or {@code null} for none
   */
  public OpenMFTask setDatecompleted(java.lang.String datecompleted) {
    this.datecompleted = datecompleted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public OpenMFTask setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public OpenMFTask setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getNewclient() {
    return newclient;
  }

  /**
   * @param newclient newclient or {@code null} for none
   */
  public OpenMFTask setNewclient(java.lang.Boolean newclient) {
    this.newclient = newclient;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public OpenMFTask setStatus(java.lang.Boolean status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTaskId() {
    return taskId;
  }

  /**
   * @param taskId taskId or {@code null} for none
   */
  public OpenMFTask setTaskId(java.lang.String taskId) {
    this.taskId = taskId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * @param timestamp timestamp or {@code null} for none
   */
  public OpenMFTask setTimestamp(java.lang.Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  @Override
  public OpenMFTask set(String fieldName, Object value) {
    return (OpenMFTask) super.set(fieldName, value);
  }

  @Override
  public OpenMFTask clone() {
    return (OpenMFTask) super.clone();
  }

}
